# Generated by Django 4.2.9 on 2024-02-08 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeaveApp', '0005_studentmodel_teachermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=50, null=True)),
                ('teacher', models.CharField(max_length=50, null=True)),
                ('message', models.CharField(max_length=300, null=True)),
            ],
        ),
    ]
