# Generated by Django 4.2.9 on 2024-02-08 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeaveApp', '0006_leavemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavemodel',
            name='verifystatus',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
